[workspace]
name = "hls-atmospheric-correction"
version = "0.1.0"
platforms = ["linux-64"]
channels = ["conda-forge"]
preview = ["pixi-build"]

[dependencies]
espa-product-formatter = { path = "packages/espa-product-formatter" }
espa-surface-reflectance = { path = "packages/espa-surface-reflectance" }
hls-libs = { path = "packages/hls-libs" }
awscli = "~=2"
