[workspace]
name = "hls-atmospheric-correction"
version = "0.1.0"
platforms = ["linux-64", "osx-arm64"]
channels = ["conda-forge"]
preview = ["pixi-build"]

[target.linux-64.dependencies]
# C packages can only be compiled on Linux x86_64
espa-product-formatter = { path = "packages/espa-product-formatter" }
espa-surface-reflectance = { path = "packages/espa-surface-reflectance" }
hls-libs = { path = "packages/hls-libs" }

[pypi-dependencies]
# Python packages, usually developed locally in this repo
# hls-utilities = { git = "https://github.com/NASA-IMPACT/hls-utilities", tag = "v1.11.1"}
# ^^^^^ FIXME: this adds a conflict with numpy/rasterio/click/boto3
hls-utilities = { git = "https://github.com/NASA-IMPACT/hls-utilities", branch = "fix/relax-deps"}

# hls-browse-imagery-creator = { git = "https://github.com/NASA-IMPACT/hls-browse_imagery", tag=  "v1.7"}
# ^^^^^ FIXME: this adds a conflict with rasterio over click
hls-browse-imagery-creator = { git = "https://github.com/NASA-IMPACT/hls-browse_imagery", branch = "fix/relax-deps"}

# hls-cmr_stac = { git = "https://github.com/NASA-IMPACT/hls-cmr_stac", tag = "v1.7" }
# ^^^^^ FIXME: this adds a conflict over rasterio
hls-cmr_stac = { git = "https://github.com/NASA-IMPACT/hls-cmr_stac", branch = "fix/relax-deps" }

hls-manifest = { git = "https://github.com/NASA-IMPACT/hls-manifest", tag = "v2.1" }

# hls-hdf_to_cog = { git = "https://github.com/NASA-IMPACT/hls-hdf_to_cog", tag = "v2.1" }
# ^^^^^ FIXME: this adds a conflict with rasterio over click
hls-hdf_to_cog = { git = "https://github.com/NASA-IMPACT/hls-hdf_to_cog", branch = "fix/relax-deps" }

# metadata-creator = { git = "https://github.com/NASA-IMPACT/hls-metadata", tag = "v2.7" }
# ^^^^^ FIXME: this adds a conflict with rasterio over click
metadata-creator = { git = "https://github.com/NASA-IMPACT/hls-metadata", branch = "fix/relax-deps" }

hls-thumbnails = { git = "https://github.com/NASA-IMPACT/hls-thumbnails", tag=  "v1.3" }

# hls-vi = { git = "https://github.com/NASA-IMPACT/hls-vi", tag = "v1.17" }
# ^^^^^ FIXME: conflict with numpy between hls-vi <> gdal (needed for gdal-bin in espa-product-formatter)
hls-vi = { git = "https://github.com/NASA-IMPACT/hls-vi", branch = "fix/relax-deps" }

[dependencies]
python = "*"
awscli = "~=2"
gdal = "*"
libgdal-jp2openjpeg = "*"
rasterio = "*"
pyproj = ">=3.7.2,<4"

[feature.dev.dependencies]
ruff = "*"
mypy = "*"
pytest = "*"

[environments]
dev = ["dev"]
