[workspace]
name = "hls-atmospheric-correction"
version = "0.1.0"
platforms = ["linux-64", "osx-arm64"]
channels = [
  "conda-forge",
  "https://hls-conda-channels.s3.amazonaws.com/hls-atmospheric-correction"
]
preview = ["pixi-build"]

[target.linux-64.dependencies]
# C packages can only be compiled on Linux x86_64
espa-product-formatter = "*"
espa-surface-reflectance = "*"
hls-libs = "*"
# fmask4 = { path = "packages/fmask4" }

[pypi-dependencies]
hls-browse-imagery-creator = { git = "https://github.com/NASA-IMPACT/hls-browse_imagery", branch = "fix/relax-deps"}
hls-cmr_stac = { git = "https://github.com/NASA-IMPACT/hls-cmr_stac", branch = "fix/relax-deps" }
hls-hdf_to_cog = { git = "https://github.com/NASA-IMPACT/hls-hdf_to_cog", branch = "fix/relax-deps" }
hls-manifest = { git = "https://github.com/NASA-IMPACT/hls-manifest", tag = "v2.1" }
metadata-creator = { git = "https://github.com/NASA-IMPACT/hls-metadata", branch = "fix/relax-deps" }
hls-thumbnails = { git = "https://github.com/NASA-IMPACT/hls-thumbnails", tag=  "v1.3" }
hls-utilities = { git = "https://github.com/NASA-IMPACT/hls-utilities", branch = "fix/relax-deps"}
# FIXME: create a sdist for hls-vi, include in release, and reference that here
hls-vi = { git = "https://github.com/NASA-IMPACT/hls-vi", branch = "fix/relax-deps" }

[dependencies]
python = ">=3.12,<4"
awscli = "~=2"
gdal = "*"
libgdal-jp2openjpeg = "*"
rasterio = "*"
pyproj = ">=3.7.2,<4"

[feature.dev.dependencies]
ruff = "*"
mypy = "*"
pytest = "*"

[feature.build.dependencies]
# Package building & publishing
pyyaml = "*"
rattler-build = "*"
rattler-index = "*"
awscli = "*"

[feature.build.tasks]
determine-targets = "python scripts/ci/determine-targets.py"
build-publish-packages = "bash scripts/ci/build-and-publish.sh"

[environments]
build = {features = ["build"], no-default-feature = true }
dev = {features = ["dev"] }
