[package]
name = "hls-libs"

[package.run-dependencies]
espa-product-formatter = { path = "../espa-product-formatter" }

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }
