context:
  version: "v3.5.1.1"

package:
  name: hls-libs
  version: ${{ version }}

build:
  number: 0
  script: build.sh

source:
  path: ./

requirements:
  build:
    - sysroot_linux-64 2.17.*
    - binutils
    - make
    - gcc
    - gfortran
  host:
    - espa-product-formatter
    - hdfeos2
    - hdfeos5
    - liblzma-devel
  run:
    - python

tests:
  - package_contents:
      files:
        exists:
          - bin/sentinel-add-fmask-sds
          - bin/landsat-add-fmask-sds
          - bin/extract_landsat_hms.py
