package:
  name: hls-libs
  version: v3.5.1.0

source:
  path: ./

requirements:
  build:
    - binutils
    - make
    - gcc
    - gfortran
  host:
    - espa-product-formatter
    - hdfeos2
    - hdfeos5
    - liblzma-devel

build:
  number: 0
  script: |
    export HDFINC="${PREFIX}/include"
    export HDFLIB="${PREFIX}/lib"
    export GCTPINC="${PREFIX}/include"
    export GCTPLIB="${PREFIX}/lib"
    export PROJINC="${PREFIX}/include"
    export PROJLIB="${PREFIX}/lib"    
    export JPEGINC="${PREFIX}/include"
    export JPEGLIB="${PREFIX}/lib"
    export SZIPINC="${PREFIX}/include"
    export SZIPLIB="${PREFIX}/lib"    
    export ZLIBINC="${PREFIX}/include"
    export ZLIBLIB="${PREFIX}/lib"    
    export ESPAINC="${PREFIX}/include"
    export ESPALIB="${PREFIX}/lib"

    export GCTPLINK="-lGctp -lm"
    export HDFLINK="-lmfhdf -ldf -lm"

    export COMMON_DIR=${SRC_DIR}/common

    export CFLAGS="-std=gnu90"

    make -j${CPU_COUNT}
    make install

tests:
  - package_contents:
      files:
        exists:
          - bin/sentinel-add-fmask-sds
          - bin/landsat-add-fmask-sds
  - script:
      - sentinel-add-fmask-sds --help | grep "fmask"

about:
  summary: Utility programs for the HLS Landsat and Sentinel-2 pipelines.
  license: MIT
