context:
  version: "v3.5.1.0"

package:
  name: espa-surface-reflectance
  version: ${{ version }}

build:
  number: 0
  script: build.sh

source:
  git: https://github.com/NASA-IMPACT/espa-surface-reflectance
  tag: ${{ version }}

requirements:
  build:
    - binutils
    - make
    - gcc
    - gfortran
  host:
    - espa-product-formatter
    - hdfeos2
    - hdfeos5
    - liblzma-devel
  run:
    - python
    - hdf4
    - hdf5 <2
    - hdfeos2
    - hdfeos5

tests:
  - package_contents:
      files:
        exists:
          - bin/lasrc
  - script:
      - lasrc --help || [ $? -eq 255 ]
