name: Release to ECR

on:
  release:
    types: [published]

env:
  AWS_REGION: us-west-2
  ECR_REPOSITORY: hls-atmospheric-correction
  BUILD_PLATFORM: linux/amd64
  FMASK_URL: https://fmask4installer.s3.amazonaws.com/Fmask_4_7_issue40_Linux_mcr.install

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # We run out of space w/o cleanup. This is less comprehensive but faster
      # than `jlumbroso/free-disk-space`
      - name: Cleanup disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Final Build & Push
      - name: Build and Push Release to ECR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: prod
          provenance: false
          sbom: false
          build-args: |
            PLATFORM=${{ env.BUILD_PLATFORM }}
            FMASK_INSTALLER=${{ env.FMASK_URL }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:cache,mode=max
