name: Build, Test, and Push Pull Requests to ECR

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  AWS_REGION: us-west-2
  ECR_REPOSITORY: hls-science-container
  BUILD_PLATFORM: linux/amd64

jobs:
  build_push_to_ecr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/free-disk-space

      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          frozen: true
          environments: dev

      - name: Lint code
        run: |
          scripts/lint
          scripts/typecheck

      - name: Run tests
        run: |
          scripts/test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}
          tags: |
            type=ref,event=pr,prefix=pr-
            type=sha,prefix=sha-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true  # Puts the image in 'docker images' for the next step
          provenance: false
          sbom: false
          target: prod
          build-args: |
            PLATFORM=${{ env.BUILD_PLATFORM }}
          tags: ${{ env.ECR_REPOSITORY }}:local
          cache-from: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:cache

      - name: Run container tests
        run: |
          docker run --rm ${{ env.ECR_REPOSITORY }}:local echo "placeholder"

      - name: Push to ECR
        if: success()
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          while IFS= read -r tag; do
            docker tag ${{ env.ECR_REPOSITORY }}:local "$tag"
            docker push "$tag"
          done <<< "$TAGS"
