name: Lint and Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          frozen: true
          environments: dev

      - name: Lint code
        run: |
          scripts/lint
          scripts/typecheck

      - name: Run tests
        run: |
          scripts/test
